### ISSUE TITLE
Exception in 2.16

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tchegito/zildo#74] opened 2015-09-23 21:32 UTC
```
java.lang.NullPointerException
at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:157)
at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:207)
at 
zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:231)
at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:114)
at zildo.server.state.ScriptManagement.render(ScriptManagement.java:128)
at zildo.server.EngineZildo.renderFrame(EngineZildo.java:183)
at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:167)
at zildo.client.Client.mainLoop(Client.java:181)
at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:105)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1263)
```

Original issue reported on code.google.com by `tcheg...@gmail.com` on 6 Jun 2015 at 11:52

**Comment by tchegito** [comment] 2016-06-10 14:34
Duplicate of Issue 90. Will be fixed there.

I close.

**Closed by tchegito** 2016-06-10 14:34 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
